language: ruby
git:
    depth: 3
cache: bundler
bundler_args: --without development
script:
    - "bundle exec rake $CHECK"
notifications:
    email: false
rvm:
    - 2.4.0
env:
    - "CHECK=docs:yard"
    # FIXME: turn this back on after more testing and refactor away cop issues
    #- "CHECK=test:rubocop"
    - "CHECK=test:spec"
